# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "username" varchar not null,
  "password" varchar not null,
  "is_admin" integer,
  "student_id" varchar,
  "student_group" varchar,
);

insert into "users" ("id","name","username","password","is_admin") values (1,'superadmin','admin','admin',1);

# --- !Downs

drop table "users" if exists;
